language: nix

nix: 2.0.4

sudo: yes

script:
  - echo "YES" | ./reflex-platform/scripts/setup
  - make

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir: docs
  on:
    branch: master
